# Generated by Django 6.0.7 on 2026-07-14 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membershipplan_duration_unit_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='memberships.membershipplan', verbose_name='Plan'),
            preserve_default=False,
        ),
    ]
