# Generated by Django 6.0.7 on 2026-07-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_plan'),
        ('payments', '0002_alter_payment_options_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.plan', verbose_name='Plan'),
        ),
    ]
