# Generated by Django 6.0.7 on 2026-07-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_initial'),
        ('payments', '0003_alter_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.plan', verbose_name='Plan'),
        ),
    ]
