# Generated by Django 6.0.7 on 2026-07-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('duration', models.IntegerField(verbose_name='Duración')),
                ('duration_type', models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses'), ('años', 'Años')], default='meses', max_length=10, verbose_name='Tipo de Duración')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan Activo')),
            ],
            options={
                'verbose_name': 'Plan de Membresía',
                'verbose_name_plural': 'Planes de Membresía',
                'ordering': ['price'],
            },
        ),
    ]
