# Generated by Django 6.0.7 on 2026-07-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Días'), ('months', 'Meses'), ('years', 'Años')], default='months', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Días'), ('months', 'Meses'), ('years', 'Años')], default='meses', max_length=10, verbose_name='Tipo de Duración'),
        ),
    ]
