# Generated by Django 6.0.7 on 2026-07-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membershipplan_duration_unit_and_more'),
        ('payments', '0003_alter_payment_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
