# Generated by Django 6.0.7 on 2026-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(choices=[(30, 'Mensual - 30 días'), (90, 'Trimestral - 90 días'), (180, 'Semestral - 180 días'), (365, 'Anual - 365 días')], default=30),
        ),
    ]
