# Generated by Django 6.0.7 on 2026-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_alter_plan_name_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(choices=[(30, 'Mensual - 30 días'), (90, 'Trimestral - 3 meses'), (180, 'Semestral - 6 meses'), (365, 'Anual - 1 año')], default=30),
        ),
    ]
