# Generated by Django 6.0.7 on 2026-07-15 16:10

import django.core.validators
from django.db import migrations, models


def backfill_duration_fields(apps, schema_editor):
    Plan = apps.get_model('memberships', 'Plan')

    for plan in Plan.objects.all():
        days = int(plan.duration_days or 0)

        if days > 0 and days % 365 == 0:
            plan.duration_unit = 'years'
            plan.duration_value = days // 365
        elif days > 0 and days % 30 == 0:
            plan.duration_unit = 'months'
            plan.duration_value = days // 30
        else:
            plan.duration_unit = 'days'
            plan.duration_value = max(days, 1)

        plan.save(update_fields=['duration_unit', 'duration_value'])


def reverse_backfill_duration_fields(apps, schema_editor):
    Plan = apps.get_model('memberships', 'Plan')

    for plan in Plan.objects.all():
        if plan.duration_unit == 'years':
            days = plan.duration_value * 365
        elif plan.duration_unit == 'months':
            days = plan.duration_value * 30
        else:
            days = plan.duration_value

        plan.duration_days = max(days, 1)
        plan.save(update_fields=['duration_days'])


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_alter_plan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Días'), ('months', 'Meses'), ('years', 'Años')], default='months', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración'),
        ),
        migrations.RunPython(backfill_duration_fields, reverse_backfill_duration_fields),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
