# Generated by Django 6.0.7 on 2026-07-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
