# Generated by Django 6.0.7 on 2026-07-15 17:05

from secrets import token_hex
from django.db import migrations, models


def populate_access_codes(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    used_codes = set(
        Member.objects.exclude(access_code='').values_list('access_code', flat=True)
    )

    for member in Member.objects.filter(access_code=''):
        while True:
            candidate = f"SG-{token_hex(4).upper()}"
            if candidate not in used_codes:
                member.access_code = candidate
                member.save(update_fields=['access_code'])
                used_codes.add(candidate)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_code',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.RunPython(populate_access_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='member',
            name='access_code',
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
    ]
